process.env.WS_NO_BUFFER_UTIL = '1';
process.env.WS_NO_UTF_8_VALIDATE = '1';
process.env.CODEBOLT_URL = process.env.CODEBOLT_URL || 'ws://localhost:31245/codebolt';
process.env.CODEBOLT_ID = process.env.CODEBOLT_ID || 'artifact-agent-test';

import type codeboltType from '@codebolt/codeboltjs';
import type { FlatUserMessage } from '@codebolt/types/sdk';

const codebolt = require('@codebolt/codeboltjs') as typeof codeboltType;

type LegacyNestedMessage = {
  threadId?: string;
  userMessage?: string;
  message?: unknown;
};

type ArtifactAgentMessage = FlatUserMessage & {
  message?: LegacyNestedMessage | string | null;
};

function getNestedMessage(message: ArtifactAgentMessage): LegacyNestedMessage | undefined {
  if (typeof message.message === 'object' && message.message !== null) {
    return message.message;
  }

  return undefined;
}

function getThreadId(message: ArtifactAgentMessage): string {
  return message.threadId || getNestedMessage(message)?.threadId || `artifact-thread-${Date.now()}`;
}

function getInvocationText(message: ArtifactAgentMessage): string | null {
  const nestedMessage = getNestedMessage(message);

  if (message.userMessage) {
    return message.userMessage;
  }

  if (nestedMessage?.userMessage) {
    return nestedMessage.userMessage;
  }

  if (typeof message.message === 'string') {
    return message.message;
  }

  if (typeof nestedMessage?.message === 'string') {
    return nestedMessage.message;
  }

  return null;
}

codebolt.onMessage(async (message: FlatUserMessage) => {
  const artifactMessage = message as ArtifactAgentMessage;
  const threadId = getThreadId(artifactMessage);
  const stamp = new Date().toISOString();

  const result = await codebolt.artifact.create({
    type: 'static_site',
    title: `Artifact Smoke Site ${stamp}`,
    description: 'Static site generated by artifact-agent during integration testing.',
    entrypoint: 'index.html',
    threadId,
    metadata: {
      source: 'artifact-agent',
      invokedWith: getInvocationText(artifactMessage),
    },
    files: [
      {
        path: 'index.html',
        content: `<!doctype html><html><head><meta charset="utf-8"><title>Artifact Smoke Site</title><style>body{font-family:system-ui;margin:40px;background:#f8fafc;color:#111827}.card{max-width:720px;border:1px solid #cbd5e1;background:white;padding:24px;border-radius:8px}code{background:#e2e8f0;padding:2px 6px;border-radius:4px}</style></head><body><main class="card"><h1>Artifact Smoke Site</h1><p id="status">Generated by <code>artifact-agent</code>.</p><p id="stamp">${stamp}</p></main></body></html>`,
        encoding: 'utf8',
      },
      {
        path: 'README.txt',
        content: `Artifact generated at ${stamp}`,
        encoding: 'utf8',
      },
    ],
  });

  return `Created artifact ${result.artifact.id}: ${result.artifact.title}`;
});
