packages:
  - packages/*
  - common/*
  - agents/*
  - providers/*
  - templateengine/*
  - tui/*
  - remoteexecutor/*
  - remoteenvironments/*
  - agentcreator/*
  - agentcreator/customnodes/*
  - actionBlocks/*
  - documentation/mainfolder
  
ignoredBuiltDependencies:
  - esbuild
  - workerd
