packages:
  - packages/*
  - common/*
  - agents/*
  - providers/*
  - templateengine/*
  - tui/*
  - remoteexecutor/*
  - remoteenvironments/*
  - agentcreator/*
  - agentcreator/customnodes/*

ignoredBuiltDependencies:
  - esbuild
  - workerd
