packages:
  - packages/*
  - common/*
  - agents/*
  - providers/*
  - templateengine/*
  - tui/*
  - remoteexecutor/*
  - remoteenvironments/*
  - remoteenvironments/wranglercontainers/container_src
  - agentcreator/*
  - agentcreator/customnodes/*
  - actionBlocks/*
  - action-blocks/*
  - documentation/mainfolder
  - documentation/internaldocuments
  - testcases
  - cli/*
  
ignoredBuiltDependencies:
  - esbuild
  - workerd
