// ================================
// INPUT/OUTPUT TYPES
// ================================

/**
 * Task information to break down
 */
export interface TaskToBreakdown {
    taskId: string;
    name: string;
    description: string;
    priority?: 'High' | 'Medium' | 'Low';
    dependencies?: string[];
    estimated_time?: string;
}

/**
 * Full plan structure for context
 */
export interface ActionPlan {
    planId: string;
    name: string;
    description: string;
    tasks: any[];
}

/**
 * Existing job for dependency analysis
 */
export interface ExistingJob {
    jobId: string;
    name: string;
    taskName?: string;
    groupId: string;
}

/**
 * Input parameters for the action block
 */
export interface BreakTaskInput {
    /** The full action plan for context */
    plan: ActionPlan;

    /** Task to break into sub-jobs */
    task: TaskToBreakdown;

    /** Existing jobs for dependency analysis */
    existingJobs?: ExistingJob[];

    /** Worker agent ID to assign jobs to */
    workerAgentId?: string;
}

/**
 * Sub-job definition generated by LLM
 */
export interface SubJobDefinition {
    /** Name of the sub-job */
    name: string;

    /** Detailed description of what needs to be done */
    description: string;

    /** Job type */
    type: 'bug' | 'feature' | 'task' | 'epic' | 'chore';

    /** Priority (1=urgent, 4=low) */
    priority: 1 | 2 | 3 | 4;

    /** Estimated effort */
    estimatedEffort: 'small' | 'medium' | 'large';

    /** Internal dependencies (names of other sub-jobs this depends on) */
    internalDependencies?: string[];

    /** External dependencies (existing job IDs this depends on) */
    externalDependencies?: string[];

    /** Labels for categorization */
    labels?: string[];
}

/**
 * Result returned by the action block
 */
export interface BreakTaskResult {
    success: boolean;
    error?: string;

    /** Task ID that was processed */
    taskId?: string;

    /** Array of sub-job definitions */
    subJobs?: SubJobDefinition[];

    /** Total count of sub-jobs */
    subJobCount?: number;
}

// ================================
// LLM RESPONSE TYPES
// ================================

export interface LLMBreakdownResponse {
    subJobs: SubJobDefinition[];
    reasoning?: string;
}
