/**
 * App-to-Agent WebSocket Schemas
 * Zod schemas for app-to-agent communication
 */

// Re-export schemas from their original source files
export {
  // Browser service response schemas
  BrowserActionResponseDataSchema,
  NewPageResponseSchema,
  ScrollResponseSchema,
  TypeResponseSchema,
  ClickResponseSchema,
  EnterResponseSchema,
  SearchResponseSchema,
  GetUrlResponseSchema,
  GoToPageResponseSchema,
  ScreenshotResponseSchema,
  HtmlReceivedSchema,
  GetMarkdownResponseSchema,
  GetContentResponseSchema,
  GetSnapShotResponseSchema,
  GetBrowserInfoResponseSchema,
  ExtractTextResponseSchema,
  BrowserServiceResponseSchema,
  // Chat service response schemas
  ChatHistoryResponseSchema,
  WaitForReplyResponseSchema,
  ConfirmationResponseSchema,
  FeedbackResponseSchema,
  // Terminal service response schemas
  CommandOutputResponseSchema,
  CommandErrorResponseSchema,
  CommandFinishResponseSchema,
  TerminalInterruptResponseSchema,
  TerminalServiceResponseSchema,
  // Project service response schemas
  GetProjectSettingsResponseSchema,
  GetProjectPathResponseSchema,
  GetRepoMapResponseSchema,
  GetEditorFileStatusResponseSchema,
  ProjectServiceResponseSchema,
  // Task service response schemas

  // LLM service response schemas
  LLMResponseSchema,
  LLMServiceResponseSchema,
  // State service response schemas
  GetAppStateResponseSchema,
  AddToAgentStateResponseSchema,
  GetAgentStateResponseSchema,
  GetProjectStateResponseSchema,
  UpdateProjectStateResponseSchema,
  StateServiceResponseSchema,
  // VectorDB service response schemas
  GetVectorResponseSchema,
  AddVectorItemResponseSchema,
  QueryVectorItemResponseSchema,
  QueryVectorItemsResponseSchema,
  VectorDBServiceResponseSchema,
  // Utils service response schemas
  EditFileAndApplyDiffResponseSchema,
  UtilsServiceResponseSchema,
  // Tokenizer service response schemas
  AddTokenResponseSchema,
  GetTokenResponseSchema,
  TokenizerServiceResponseSchema,
  // MCP service response schemas
  GetEnabledToolBoxesResponseSchema,
  GetLocalToolBoxesResponseSchema,
  GetAvailableToolBoxesResponseSchema,
  SearchAvailableToolBoxesResponseSchema,
  ListToolsFromToolBoxesResponseSchema,
  ConfigureToolBoxResponseSchema,
  GetToolsResponseSchema,
  ExecuteToolResponseSchema,
  MCPServiceResponseSchema,
  // Debug service response schemas
  DebugAddLogResponseSchema,
  OpenDebugBrowserResponseSchema,
  GetDebugLogsResponseSchema,
  DebugServiceResponseSchema,
  // DB Memory service response schemas
  MemorySetResponseSchema,
  MemoryGetResponseSchema,
  DBMemoryServiceResponseSchema,
  // Code Utils service response schemas
  GetJsTreeResponseSchema,
  GetAllFilesAsMarkdownResponseSchema,
  MatchProblemResponseSchema,
  GetMatcherListTreeResponseSchema,
  GetMatchDetailResponseSchema,
  CodeUtilsServiceResponseSchema,
  // Crawler service response schemas
  CrawlResponseSchema,
  CrawlerServiceResponseSchema,
  // FS service response schemas
  CreateFileSuccessResponseSchema,
  CreateFileErrorResponseSchema,
  CreateFolderSuccessResponseSchema,
  CreateFolderErrorResponseSchema,
  ReadFileSuccessResponseSchema,
  ReadFileSuccessResultResponseSchema,
  UpdateFileSuccessResponseSchema,
  UpdateFileErrorResponseSchema,
  DeleteFileSuccessResponseSchema,
  DeleteFileErrorResponseSchema,
  DeleteFolderSuccessResponseSchema,
  DeleteFolderErrorResponseSchema,
  FileListSuccessResponseSchema,
  FileListErrorResponseSchema,
  SearchFilesSuccessResponseSchema,
  SearchFilesErrorResponseSchema,
  WriteToFileSuccessResponseSchema,
  WriteToFileErrorResponseSchema,
  GrepSearchSuccessResponseSchema,
  GrepSearchErrorResponseSchema,
  ListCodeDefinitionNamesSuccessResponseSchema,
  ListCodeDefinitionNamesErrorResponseSchema,
  FileSearchSuccessResponseSchema,
  FileSearchErrorResponseSchema,
  EditFileAndApplyDiffSuccessResponseSchema,
  EditFileAndApplyDiffErrorResponseSchema,
  FsServiceResponseSchema,
  // Git service response schemas
  GitInitResponseSchema,
  GitPullResponseSchema,
  GitPushResponseSchema,
  GitStatusResponseSchema,
  GitAddResponseSchema,
  GitCommitResponseSchema,
  GitCheckoutResponseSchema,
  GitBranchResponseSchema,
  GitLogsResponseSchema,
  GitDiffResponseSchema,
  GitServiceResponseSchema,
  // Agent service response schemas
  FindAgentByTaskResponseSchema,
  ListAgentsResponseSchema,
  AgentsDetailResponseSchema,
  TaskCompletionResponseSchema,
  AgentServiceErrorResponseSchema,
  AgentServiceResponseSchema,
  GetSummarizeAllResponseSchema,
  GetSummarizeResponseSchema,

} from './wstypes/app-to-agent-ws/indexResponses';

// Task service response schemas and types
export {
  taskStatusSchema,
  taskPrioritySchema,
  taskSchema,
  createTaskResponseSchema,
  updateTaskResponseSchema,
  deleteTaskResponseSchema,
  getTaskResponseSchema,
  listTasksResponseSchema,
  assignAgentResponseSchema,
  startTaskWithAgentResponseSchema,
  taskErrorResponseSchema,
  // Legacy schemas
  addTaskResponseSchema,
  updateTasksResponseSchema,
  addSubTaskResponseSchema,
  updateSubTaskResponseSchema,
  getTasksByCategoryResponseSchema,
  createTasksFromMarkdownResponseSchema,
  exportTasksToMarkdownResponseSchema,
  taskServiceResponseSchema,
  // Task service response types
  type TaskStatus,
  type TaskPriority,
  type Task,
  type CreateTaskResponse,
  type UpdateTaskResponse,
  type DeleteTaskResponse,
  type GetTaskResponse,
  type ListTasksResponse,
  type AssignAgentResponse,
  type StartTaskWithAgentResponse,
  type TaskErrorResponse,
  // Legacy types
  type AddTaskResponse,
  type UpdateTasksResponse,
  type AddSubTaskResponse,
  type UpdateSubTaskResponse,
  type GetTasksByCategoryResponse,
  type CreateTasksFromMarkdownResponse,
  type ExportTasksToMarkdownResponse,
  type TaskServiceResponse
} from './wstypes/app-to-agent-ws/taskServiceResponses';

// Thread service response schemas and types
export {
  threadStatusSchema,
  threadStepStatusSchema,
  threadPrioritySchema,
  threadTypeSchema,
  executionTypeSchema,
  environmentTypeSchema,
  startOptionSchema,
  messageTypeSchema,
  threadStepResponseSchema,
  threadMessageResponseSchema,
  threadMemoryResponseSchema,
  threadResponseSchema,
  createThreadResponseSchema,
  updateThreadResponseSchema,
  deleteThreadResponseSchema,
  getThreadResponseSchema,
  listThreadsResponseSchema,
  startThreadResponseSchema,
  updateThreadStatusResponseSchema,
  getThreadMessagesResponseSchema,
  threadErrorResponseSchema,
  threadAgentStartedResponseSchema,
  threadAgentStartFailedResponseSchema,
  threadServiceResponseSchema,
  // Thread service response types
  type ThreadStatus,
  type ThreadStepStatus,
  type ThreadPriority,
  type ThreadType,
  type ExecutionType,
  type EnvironmentType,
  type StartOption,
  type MessageType,
  type ThreadStepResponse,
  type ThreadMessageResponse,
  type ThreadMemoryResponse,
  type ThreadResponse,
  type CreateThreadResponse,
  type UpdateThreadResponse,
  type DeleteThreadResponse,
  type GetThreadResponse,
  type ListThreadsResponse,
  type StartThreadResponse,
  type UpdateThreadStatusResponse,
  type GetThreadMessagesResponse,
  type ThreadErrorResponse,
  type ThreadAgentStartedResponse,
  type ThreadAgentStartFailedResponse,
  type ThreadServiceResponse
} from './wstypes/app-to-agent-ws/threadServiceResponses';

