name = "codebolt-wrangler-ws"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "PROXY_HUB", class_name = "ProxyHub" }
]

[[migrations]]
tag = "v1"
new_classes = ["ProxyHub"]
