import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  jsapiSidebar: [{type: 'autogenerated', dirName: 'api'}],
  userSidebar: [{type: 'autogenerated', dirName: 'user'}],
  devSidebar: [{type: 'autogenerated', dirName: 'developer'}],
  // appSidebar: [{type: 'autogenerated', dirName: 'apps'}],
  // toolSidebar: [{type: 'autogenerated', dirName: 'tools'}],

  // But you can create a sidebar manually
  
  // jsapiSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Fs',
  //     items: [
  //       {
  //         type: 'link',
  //         label: 'Create File',
  //         href: '/docs/main',
  //       },
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Docusaurus',
  //     items: [
  //       {
  //         type: 'doc',
  //         id: 'main',
  //       },
  //       {
  //         type: 'doc',
  //         id: 'gettingstarted',
  //       },
  //     ],
  //   },
  //   'gettingstarted'
  // ],
};

export default sidebars;
