version: '3.8'

services:
  dockerserver:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: codebolt-dockerserver
    ports:
      - "3001:3001"
    volumes:
      - shared-data:/app/shared
      - logs:/app/logs
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - PORT=3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - codebolt-network

volumes:
  shared-data:
    driver: local
  logs:
    driver: local

networks:
  codebolt-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16